name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-2'
        EC2_HOST: '54.180.97.182'
        KEY_FILE: ${{ secrets.KEY_FILE }}
      run: |
        sudo apt-get install -y jq
        scp -i $KEY_FILE -o StrictHostKeyChecking=no -r . ec2-user@$EC2_HOST:~/myapp
        ssh -i $KEY_FILE -o StrictHostKeyChecking=no ec2-user@$EC2_HOST << 'EOF'
          cd ~/EVI-ION-website
          npm install
          pm2 restart all || pm2 start server.js
        EOF
