name: Deploy Backend (Windows)

on:
  push:
    branches:
      - main # main 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: 작업 디렉토리 확인 (디버깅)
        run: |
          echo "현재 디렉토리:"
          Get-Location
          echo "디렉토리 목록:"
          Get-ChildItem -Force

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 의존성 설치
        working-directory: evision-backend
        run: npm install

      - name: 테스트 실행 (테스트 실패 시 무시)
        working-directory: evision-backend
        run: npm test || echo "테스트 실패 - 계속 진행"

      - name: 서버 실행 (백그라운드 실행 후 종료)
        working-directory: evision-backend
        run: |
          Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "start"
          Start-Sleep -Seconds 10
          echo "서버 실행 후 10초 후 종료"
